### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by St3rling0x** [Monaize/docker-insight#1]
when i run docker-compose up i get the following error
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Com

**Comment by askz** [comment]
Hi, I just updated the readme, you'll need to have at least:

* Docker Engine 1.12.0+
* Docker Compose 1.9.0+

**Comment by askz** [comment]
Closing since its resolved.
